model:
  class_path: AutoregressiveFlow
  init_args:
    lattice_size: 8
    n_mixture: 12
    weighted: false
    net_shape: [24]
    net_activation: Tanh
    ramp_pow: 2

target:
  beta: 3.
  lattice_size: 8
  lattice_dim: 1

train:
  n_steps: 2000
  batch_size: 4096
